package com.kltyton.autoseamblend.compat.continuity.authoring.materialize;

import com.kltyton.autoseamblend.authoring.model.ManagedAuthoringDraft;
import com.kltyton.autoseamblend.selection.method.ConnectionMethod;
import java.util.List;
import java.util.Objects;
import net.minecraft.resources.ResourceLocation;

/**
 * 中文：集中 Continuity/MCPatcher 创作输出的资源路径与 tiles 表达式规划。
 *
 * <p>English: Centralizes Continuity/MCPatcher authoring-output resource paths and tile-expression
 * planning.
 *
 * <p>这些规则只处理项目值对象和资源 ID，不访问 Loader、Minecraft 渲染对象或原生处理器。
 * English: These rules operate only on project value objects and resource IDs; they do not access a
 * Loader, Minecraft render objects, or native processors.
 */
public final class ContinuityMaterializePathPlanner {
    private static final String RESERVED_PREFIX = "continuity_reserved/";

    private ContinuityMaterializePathPlanner() {}

    /**
     * 中文：把 MCPatcher 的 assets 路径转换为资源 ID。
     * English: Converts an MCPatcher assets path into its resource ID.
     */
    public static ResourceLocation documentResourceId(String documentPath) {
        Objects.requireNonNull(documentPath, "documentPath");
        String[] segments = documentPath.split("/", 3);
        if (segments.length != 3
                || !"assets".equals(segments[0])
                || segments[1].isBlank()
                || segments[2].isBlank()) {
            throw new IllegalArgumentException(
                    "MCPatcher document path is not inside assets");
        }
        return new ResourceLocation(segments[1], segments[2]);
    }

    /**
     * 中文：规划原生槽位 PNG 的资源包路径；连续性保留精灵使用 optifine 目录。
     * English: Plans the resource-pack path for a native slot PNG; Continuity-reserved sprites use
     * the optifine directory.
     */
    public static String nativeTexturePath(String encodedId) {
        Objects.requireNonNull(encodedId, "encodedId");
        ResourceLocation id = new ResourceLocation(encodedId);
        String path = id.getPath();
        if (path.startsWith(RESERVED_PREFIX)) {
            return "assets/"
                    + id.getNamespace()
                    + "/optifine/"
                    + path.substring(RESERVED_PREFIX.length())
                    + ".png";
        }
        return "assets/"
                + id.getNamespace()
                + "/textures/"
                + path
                + ".png";
    }

    /**
     * 中文：为没有原生 PNG 的槽位规划与属性文档同目录的生成文件名。
     * English: Plans the generated filename beside the properties document for a slot without a
     * native PNG.
     */
    public static String generatedTexturePath(String documentPath, int slot) {
        Objects.requireNonNull(documentPath, "documentPath");
        if (slot < 0) {
            throw new IllegalArgumentException("slot must be non-negative");
        }
        int slash = documentPath.lastIndexOf('/');
        if (slash < 0) {
            throw new IllegalArgumentException(
                    "MCPatcher document has no parent directory");
        }
        return documentPath.substring(0, slash + 1) + slot + ".png";
    }

    /**
     * 中文：规划编辑器生成的稳定内部纹理 ID。
     * English: Plans the stable internal texture ID generated by the editor.
     */
    public static String editorTextureId(
            ManagedAuthoringDraft draft,
            ConnectionMethod method,
            int slot) {
        Objects.requireNonNull(draft, "draft");
        Objects.requireNonNull(method, "method");
        if (slot < 0) {
            throw new IllegalArgumentException("slot must be non-negative");
        }
        ResourceLocation blockId = new ResourceLocation(draft.targetBlockId());
        return "autoseamblend:editor/mcpatcher/"
                + method.serializedName()
                + '/'
                + blockId.getNamespace()
                + '/'
                + blockId.getPath()
                + '/'
                + slot;
    }

    /**
     * 中文：把有序槽位域压缩为 MCPatcher tiles 表达式。
     * English: Compresses an ordered slot domain into an MCPatcher tiles expression.
     */
    public static String tilesExpression(List<Integer> domain) {
        Objects.requireNonNull(domain, "domain");
        if (domain.isEmpty()) {
            throw new IllegalArgumentException("slot domain must not be empty");
        }
        if (domain.stream().anyMatch(slot -> slot == null || slot < 0)) {
            throw new IllegalArgumentException("slot domain must contain non-negative slots");
        }
        if (domain.size() == 1) {
            return Integer.toString(domain.get(0));
        }
        return domain.get(0) + "-" + domain.get(domain.size() - 1);
    }
}
