package com.kltyton.autoseamblend.authoring.export;

import com.kltyton.autoseamblend.authoring.model.ManagedAuthoringFile;
import com.kltyton.autoseamblend.engine.EngineFamily;
import com.kltyton.autoseamblend.export.managed.ManagedExportIr;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

/**
 * 中文：跨 Loader 的原生导出文档装配；实际格式 baked 转换通过回调留在 Loader/引擎边界。
 * English: Loader-neutral native-export document assembly; format-specific baked conversion
 * remains at the Loader/engine boundary through a callback.
 */
public final class ManagedExportDocumentAssembly {
    private ManagedExportDocumentAssembly() {}

    /**
     * 中文：选择捕获主文档，或从首次保存模板创建主文档，并验证引擎来源。
     * English: Selects a captured principal document or creates one from the first-save template,
     * then validates its engine provenance.
     */
    public static NativeDocumentSnapshot principal(
            EngineFamily family,
            ManagedAuthoringFile template,
            Optional<NativeDocumentSnapshot> captured) {
        Objects.requireNonNull(family, "family");
        Objects.requireNonNull(template, "template");
        Objects.requireNonNull(captured, "captured");
        NativeDocumentSnapshot document = captured.orElseGet(() ->
                new NativeDocumentSnapshot(
                        family,
                        template.relativePath(),
                        template.content(),
                        Optional.empty()));
        if (document.family() != family) {
            throw new IllegalArgumentException(
                    "EXPORT_NATIVE_DOCUMENT_ENGINE_CHANGED");
        }
        return document;
    }

    /**
     * 中文：把捕获陪文件追加到 authoring/baked IR，排除主文档和本批次生成路径。
     * English: Appends captured companions to the authoring/baked IR while excluding the
     * principal document and paths generated by the current batch.
     */
    public static void appendCompanionDocuments(
            List<ManagedExportIr.Document> documents,
            NativeDocumentSnapshot principal,
            Set<String> excludedPaths,
            CompanionBaker baked) throws IOException {
        Objects.requireNonNull(documents, "documents");
        Objects.requireNonNull(principal, "principal");
        Objects.requireNonNull(excludedPaths, "excludedPaths");
        Objects.requireNonNull(baked, "baked");
        LinkedHashSet<String> excluded = new LinkedHashSet<>(excludedPaths);
        excluded.add(principal.documentPath());
        for (Map.Entry<String, byte[]> entry
                : principal.companionDocuments().entrySet()) {
            String path = entry.getKey();
            if (excluded.contains(path)) {
                continue;
            }
            byte[] authoring = entry.getValue();
            documents.add(new ManagedExportIr.Document(
                    path,
                    authoring,
                    path,
                    baked.baked(principal, path, authoring)));
        }
    }

    /**
     * 中文：只在源材质存在动画元数据时追加同路径 `.mcmeta`，并保持两种导出字节一致。
     * English: Appends a same-path `.mcmeta` only when source metadata exists, preserving the
     * same bytes for both export profiles.
     */
    public static void appendMetadata(
            List<ManagedExportIr.Document> documents,
            String pngPath,
            byte[] metadata) {
        Objects.requireNonNull(documents, "documents");
        metadataDocument(pngPath, metadata).ifPresent(documents::add);
    }

    /**
     * 中文：构造可插入任意去重文档集合的元数据文档；空元数据返回空。
     * English: Builds a metadata document for insertion into any deduplicating document
     * collection; empty metadata returns empty.
     */
    public static Optional<ManagedExportIr.Document> metadataDocument(
            String pngPath,
            byte[] metadata) {
        Objects.requireNonNull(pngPath, "pngPath");
        Objects.requireNonNull(metadata, "metadata");
        if (metadata.length == 0) {
            return Optional.empty();
        }
        return Optional.of(new ManagedExportIr.Document(
                pngPath + ".mcmeta",
                metadata,
                pngPath + ".mcmeta",
                metadata));
    }

    @FunctionalInterface
    public interface CompanionBaker {
        /**
         * 中文：生成陪文件 baked 字节；输入字节和快照均为只读语义。
         * English: Produces baked companion bytes; the snapshot and source bytes are read-only
         * inputs by contract.
         */
        byte[] baked(
                NativeDocumentSnapshot principal,
                String path,
                byte[] authoring) throws IOException;
    }
}
